### ISSUE TITLE
issue in deploying to render 

### ISSUE THREAD

**Issue by thinkbyit** [TamilanBotsZ/AwesomeFilterPro#20]
![image](https://user-images.githubusercontent.com/101200766/219672921-7449d049-cac9-4c63-b266-217efa9abaaa.png)

kindly , tell me the solution ....

i have followed all the steps

**Comment by TamilanBotsZ** [comment]
No build comment added

**Comment by thinkbyit** [comment]
means ?

as you have written in the repo of render branch , i have done that only
